# Generated by Django 5.0 on 2023-12-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'), # this will not persist it in the models.py though - it's just a one-off for the migration
            preserve_default=False,
        ),
    ]
