# Generated by Django 5.0 on 2023-12-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer_store_custo_last_na_2e448d_idx'),
    ]

    operations = [
        migrations.RunSQL(
            """
            --sql 
            insert into store_collection (title)
            values ('collection1')
            --end-sql
            """, # for updating the database
            """
            --sql
            delete from store_collection 
            where title = 'collection1'
            --end-sql
            """ # enables us to revert the change above
        )
    ]
