# Generated by Django 5.0 on 2023-12-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_orders', 'Can cancel orders')]},
        ),
    ]
