# Generated by Django 5.0 on 2023-12-27 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_cart_id_alter_cart_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='temp_id',
            new_name='id',
        ),
    ]
