# Generated by Django 5.0 on 2023-12-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_rename_temp_id_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
